### ISSUE TITLE
Cannot download gems

### ISSUE THREAD

**Issue by eirvandelden** [regedor/Evermark#2]
**What I did**
- Download EverMark using download link on website
- Open EverMark

**What I expected**
EverMark to download dependencies and start

**What I got**
````
sh: gems/gems/bundle*/bin/bundle: No such file or directory
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- rack (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Applications/EverMark.app/Contents/Resources/script:57:in `<main>'
````

Note, I do have rbenv installed.

**Comment by gopalvasudev** [comment]
Same issue. Have installed Evermark before without any issues. Please resolve.

**Comment by mostlyjeff** [comment]
Same issue. I'm also running rbenv. Is there anything else I can provide to start troubleshooting this?

**Comment by regedor** [comment]
Hey, guys sorry for the delay in my response, Evermark is a small project of mine and was lately overloaded with work at Freeletics, end up not seeing this issue until now.

I just merged the pull request from @mostlyjeff I hope that fixes your problems, if not let me know I will try to find a way to fix them.
